### ISSUE TITLE
Multiselect dropdown close on focus out not working on MBKit Modal

### ISSUE THREAD

**Issue by amitkumar4942** [mindbody/mbkit#133]
MBKit Multiselect drop-down does not close on focus out, when we use in MBKit modal.
Due to the changes in latest version(17.0.0 +) of the react-dom, document click is not working.

document.addEventListener('click', function() {
  // This custom handler will no longer receive clicks
  // from React components that called e.stopPropagation()
});

https://github.com/mindbody/mbkit/blob/master/packages/Select/src/MultiSelect.tsx#L54

https://reactjs.org/blog/2020/08/10/react-v17-rc.html
<img width="644" alt="react-17-issue" src="https://user-images.githubusercontent.com/84441021/118779987-38fcaf80-b8a9-11eb-97a0-ced0b431ce34.PNG">

**Comment by czaas** [comment]
Fixed in https://github.com/mindbody/mbkit/pull/134

Thanks @amitkumar4942!
