### ISSUE TITLE
Visited Links show up as red (intentional?)

### ISSUE THREAD

**Issue by kboedges** [mindbody/mbkit#99]
Bringing this up because the red comes across as an alert and draws a lot of attention. The link starts as blue and becomes red after it is clicked on.
![Screen Shot 2020-04-24 at 2 10 39 PM](https://user-images.githubusercontent.com/8322476/80248382-64c14d80-8635-11ea-9bd1-69a4f533e33d.png)

**Comment by czaas** [comment]
@kboedges Yes, this is intentional. You can override it with the `:visited` css state

Part of accessibility requires links to show the visited state of a link.
